-- printscan-cloud 베이스라인 스키마 (Postgres).
-- Hibernate(ddl-auto=create) 가 실 Postgres 16 에 생성한 스키마를 pg_dump 로 추출·정제.
-- 이후 prod 는 ddl-auto=validate — 엔티티와 이 스키마가 불일치하면 부팅 실패(안전장치).
-- 신규 컬럼/테이블은 V2__*.sql 로 추가(이 파일 수정 금지: Flyway 체크섬).

CREATE TABLE cloud_template (
    dpi integer,
    height_mm double precision NOT NULL,
    width_mm double precision NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    org_id bigint,
    updated_at timestamp(6) without time zone,
    elements_json character varying(32600),
    name character varying(255) NOT NULL,
    CONSTRAINT cloud_template_pkey PRIMARY KEY (id)
);
CREATE INDEX ix_tpl_org ON cloud_template USING btree (org_id);

CREATE TABLE consumption_log (
    from_print boolean NOT NULL,
    qty integer NOT NULL,
    at timestamp(6) without time zone,
    device_id bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    org_id bigint,
    code character varying(255),
    line character varying(255),
    operator character varying(255),
    CONSTRAINT consumption_log_pkey PRIMARY KEY (id)
);
CREATE INDEX ix_consume_at ON consumption_log USING btree (at);

CREATE TABLE device (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    last_seen_at timestamp(6) without time zone,
    org_id bigint,
    print_count bigint NOT NULL,
    registered_at timestamp(6) without time zone,
    device_token character varying(255),
    line character varying(255),
    name character varying(255),
    printer_mode character varying(255),
    CONSTRAINT device_pkey PRIMARY KEY (id),
    CONSTRAINT device_device_token_key UNIQUE (device_token)
);

CREATE TABLE inventory_snapshot (
    quantity integer NOT NULL,
    device_id bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    org_id bigint,
    updated_at timestamp(6) without time zone,
    code character varying(255),
    name character varying(255),
    CONSTRAINT inventory_snapshot_pkey PRIMARY KEY (id),
    CONSTRAINT inventory_snapshot_device_id_code_key UNIQUE (device_id, code)
);

CREATE TABLE organization (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    api_key character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT organization_pkey PRIMARY KEY (id),
    CONSTRAINT organization_api_key_key UNIQUE (api_key)
);

CREATE TABLE print_job (
    copies integer NOT NULL,
    dpi integer,
    height_mm double precision NOT NULL,
    serial_count integer,
    serial_pad integer,
    serial_start integer,
    width_mm double precision NOT NULL,
    created_at timestamp(6) without time zone,
    device_id bigint,
    done_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    org_id bigint,
    sent_at timestamp(6) without time zone,
    elements_json character varying(32600),
    variables_json character varying(32600),
    message character varying(255),
    seq_var character varying(255),
    serial_prefix character varying(255),
    status character varying(255),
    CONSTRAINT print_job_pkey PRIMARY KEY (id),
    CONSTRAINT print_job_status_check CHECK (status IN ('QUEUED', 'SENT', 'DONE', 'FAILED'))
);
CREATE INDEX ix_job_device_status ON print_job USING btree (device_id, status);
